import { NumberFormatter } from "mendix";
import { ReactElement, useMemo, useRef } from "react";

import { Slider as SliderComponent } from "./Slider";
import { SliderContainerProps } from "../../typings/SliderProps";
import { createHandleRender } from "../utils/createHandleRender";
import { createValueFormatter, getSliderLabel } from "../utils/helpers";
import { getStyleProp, isVertical, maxProp, minProp, stepProp } from "../utils/prop-utils";
import { useMarks } from "../utils/useMarks";
import { useNumber } from "../utils/useNumber";
import { useOnChangeDebounced } from "../utils/useOnChangeDebounced";

export function Container(props: SliderContainerProps): ReactElement {
    const min = useNumber(minProp(props));
    const max = useNumber(maxProp(props));
    const step = useNumber(stepProp(props));

    if (min.loading || max.loading || step.loading || props.valueAttribute.status === "loading") {
        return <SliderComponent disabled />;
    }

    return <InnerContainer min={min.value} max={max.value} step={step.value} {...props} />;
}

interface InnerContainerProps extends SliderContainerProps {
    min: number | undefined;
    max: number | undefined;
    step: number | undefined;
}

function InnerContainer(props: InnerContainerProps): ReactElement {
    const sliderRef = useRef<HTMLDivElement>(null);

    const format = useMemo(
        () => createValueFormatter(props.valueAttribute.formatter as NumberFormatter, props.decimalPlaces),
        [props.valueAttribute.formatter, props.decimalPlaces]
    );

    const handleRender = useMemo(
        () =>
            props.showTooltip
                ? createHandleRender({
                      tooltip: props.tooltip,
                      tooltipType: props.tooltipType,
                      tooltipAlwaysVisible: props.tooltipAlwaysVisible,
                      sliderRef,
                      format
                  })
                : undefined,
        [props.showTooltip, props.tooltip, props.tooltipType, props.tooltipAlwaysVisible, format]
    );

    const { onChange } = useOnChangeDebounced({ valueAttribute: props.valueAttribute, onChange: props.onChange });
    const marks = useMarks({
        noOfMarkers: props.noOfMarkers,
        decimalPlaces: props.decimalPlaces,
        format,
        min: props.min,
        max: props.max
    });
    // Label generated by systemProperty has the format: {widgetId}-label
    const ariaLabelledByForHandle = `${props.id}-label`;
    const sliderLabel = getSliderLabel(props.id);
    const hasLabel = useMemo(() => Boolean(sliderLabel), [sliderLabel]);

    return (
        <SliderComponent
            disabled={props.valueAttribute.readOnly}
            rootStyle={getStyleProp({
                orientation: props.orientation,
                height: props.height,
                heightUnit: props.heightUnit
            })}
            vertical={isVertical(props)}
            value={props.valueAttribute.value?.toNumber()}
            min={props.min}
            max={props.max}
            step={props.step}
            onChange={onChange}
            marks={marks}
            ariaLabelledByForHandle={hasLabel ? ariaLabelledByForHandle : undefined}
            handleRender={handleRender}
            ref={sliderRef}
        />
    );
}
