import { DatagridContainerProps } from "./DatagridProps";

/** Type to declare props available through main gate. */
export type MainGateProps = Pick<
    DatagridContainerProps,
    | "allSelectedText"
    | "class"
    | "clearSelectionButtonLabel"
    | "columns"
    | "configurationAttribute"
    | "configurationStorageType"
    | "customRowKey"
    | "datasource"
    | "dynamicPage"
    | "dynamicPageSize"
    | "emptyPlaceholder"
    | "enableSelectAll"
    | "filtersPlaceholder"
    | "itemSelection"
    | "loadMoreButtonCaption"
    | "name"
    | "onClick"
    | "onClickTrigger"
    | "onSelectionChange"
    | "pageSize"
    | "pagination"
    | "pagingPosition"
    | "refreshIndicator"
    | "refreshInterval"
    | "rowClass"
    | "selectAllTemplate"
    | "selectAllText"
    | "selectedCountTemplateSingular"
    | "selectedCountTemplatePlural"
    | "selectionCounterPosition"
    | "showNumberOfRows"
    | "showPagingButtons"
    | "storeFiltersInPersonalization"
    | "style"
    | "texts"
    | "totalCountValue"
    | "useCustomPagination"
    | "customPagination"
>;
