import { DatagridContainerProps } from "./DatagridProps";

/** Type to declare props available through main gate. */
export type MainGateProps = Pick<
    DatagridContainerProps,
    | "allSelectedText"
    | "cancelExportLabel"
    | "cancelSelectionLabel"
    | "class"
    | "clearSelectionButtonLabel"
    | "columns"
    | "configurationAttribute"
    | "configurationStorageType"
    | "datasource"
    | "dynamicPage"
    | "dynamicPageSize"
    | "emptyPlaceholder"
    | "enableSelectAll"
    | "exportDialogLabel"
    | "filterSectionTitle"
    | "filtersPlaceholder"
    | "itemSelection"
    | "loadMoreButtonCaption"
    | "name"
    | "onClick"
    | "onClickTrigger"
    | "onSelectionChange"
    | "pageSize"
    | "pagination"
    | "pagingPosition"
    | "refreshIndicator"
    | "refreshInterval"
    | "rowClass"
    | "selectAllRowsLabel"
    | "selectAllTemplate"
    | "selectAllText"
    | "selectionCounterPosition"
    | "selectRowLabel"
    | "singleSelectionColumnLabel"
    | "showNumberOfRows"
    | "showPagingButtons"
    | "storeFiltersInPersonalization"
    | "style"
    | "totalCountValue"
    | "useCustomPagination"
    | "customPagination"
>;
