// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import "mx-global";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} targetName - Name of the widget for which filters should be reset. Valid targets are: Data grid 2, Gallery. You can find filter name in widget settings in the "Common" group (Properties>Common>Name).
 * @param {boolean} setToDefault - Set to default value
 * @returns {Promise.<void>}
 */
export async function Reset_All_Filters(targetName, setToDefault) {
	// BEGIN USER CODE
    const plugin = window["com.mendix.widgets.web.plugin.externalEvents"];
    if (plugin) {
        plugin.emit(targetName, "reset.filters", setToDefault);
    }
	// END USER CODE
}
