// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} targetName - Name of the filter to reset. Valid targets are: Number filter, Date filter, Text filter, Drop-down filter. You can find filter name in widget settings in the "Common" group (Properties>Common>Name).
 * @param {boolean} useDefaultValue
 * @param {"DataWidgets.Filter_Operators.contains"|"DataWidgets.Filter_Operators.startsWith"|"DataWidgets.Filter_Operators.endsWith"|"DataWidgets.Filter_Operators.greater"|"DataWidgets.Filter_Operators.greaterEqual"|"DataWidgets.Filter_Operators.equal"|"DataWidgets.Filter_Operators.notEqual"|"DataWidgets.Filter_Operators.smaller"|"DataWidgets.Filter_Operators.smallerEqual"|"DataWidgets.Filter_Operators.empty"|"DataWidgets.Filter_Operators.notEmpty"} operators - Selected operators value.
 * @param {string} stringValue
 * @param {Big} numberValue
 * @param {boolean} booleanValue
 * @param {Date} dateTimeValue
 * @param {Date} dateTimeValue2
 * @returns {Promise.<void>}
 */
export async function Set_Filter(targetName, useDefaultValue, operators, stringValue, numberValue, booleanValue, dateTimeValue, dateTimeValue2) {
	// BEGIN USER CODE
	const plugin = window["com.mendix.widgets.web.plugin.externalEvents"];
    if (plugin) {
        plugin.emit(targetName, "set.value", useDefaultValue, {
			operators, stringValue, numberValue, booleanValue, dateTimeValue, dateTimeValue2
		});
    }
	// END USER CODE
}
