import { createInjectionHooks } from "brandi-react";
import { CORE_TOKENS as CORE, DG_TOKENS as DG } from "../tokens";

export const [useBasicData] = createInjectionHooks(DG.basicDate);
export const [useColumnsStore] = createInjectionHooks(CORE.columnsStore);
export const [useDatagridConfig] = createInjectionHooks(CORE.config);
export const [useDatagridFilterAPI] = createInjectionHooks(DG.filterAPI);
export const [useExportProgressService] = createInjectionHooks(DG.exportProgressService);
export const [useLoaderViewModel] = createInjectionHooks(DG.loaderVM);
export const [useMainGate] = createInjectionHooks(CORE.mainGate);
export const [usePaginationVM] = createInjectionHooks(DG.paginationVM);
export const [useGridSizeStore] = createInjectionHooks(DG.gridSizeStore);
export const [useSelectionHelper] = createInjectionHooks(DG.selectionHelper);
export const [useGridStyle] = createInjectionHooks(DG.gridColumnsStyle);
export const [useQueryService] = createInjectionHooks(DG.query);
export const [useVisibleColumnsCount] = createInjectionHooks(CORE.atoms.visibleColumnsCount);
export const [useItemCount] = createInjectionHooks(CORE.atoms.itemCount);
export const [useColumn] = createInjectionHooks(CORE.column);
export const [useTexts] = createInjectionHooks(CORE.texts);
export const [useRowClass] = createInjectionHooks(DG.rowClass);
export const [useDatagridRootVM] = createInjectionHooks(DG.datagridRootVM);
export const [useRows] = createInjectionHooks(CORE.rows);
export const [useSelectActions] = createInjectionHooks(DG.selectActions);
export const [useCustomPagination] = createInjectionHooks(DG.customPagination);
export const [usePaginationConfig] = createInjectionHooks(DG.paginationConfig);
export const [useHeaderDragnDropVM] = createInjectionHooks(DG.headerDragnDropVM);
export const [useClickActionHelper] = createInjectionHooks(DG.clickActionHelper);
export const [useFocusService] = createInjectionHooks(DG.focusService);
export const [useCheckboxEventsHandler] = createInjectionHooks(DG.checkboxEventsHandler);
export const [useCellEventsHandler] = createInjectionHooks(DG.cellEventsHandler);
