name: Main workflow

on:
  workflow_call:

env:
  since_flag: ${{ github.event_name == 'pull_request' && '...[origin/${{ github.base_ref }}]' || '' }}

jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - run: env